version: 2
updates:
  # Enable version updates for Composer (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
      include: "scope"
    reviewers:
      - "episciences-team"
    assignees:
      - "episciences-team"
    labels:
      - "dependencies"
      - "php"

  # Enable version updates for npm (JavaScript)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    reviewers:
      - "episciences-team"
    assignees:
      - "episciences-team"
    labels:
      - "dependencies"
      - "javascript"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker/php-fpm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "episciences-team"
    assignees:
      - "episciences-team"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker/apache"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "episciences-team"
    assignees:
      - "episciences-team"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "episciences-team"
    assignees:
      - "episciences-team"
    labels:
      - "dependencies"
      - "github-actions"